/**
 * Real-time Pulmonary Mechanics & Bag-Valve-Mask (BVM) Ventilation Dynamics
 * Compliant with AHA BLS 2020-2025, ERC 2021, and ILCOR Pulmonary Standards.
 */

export interface AirwayState {
  headTiltAngleDeg: number; // 0 (flat/neutral) to 45 (optimal hyperextension)
  jawThrustActive: boolean;
  isAirwayOpen: boolean;
  airwayResistanceCmH2O: number; // normal: 2-4, occluded: 40-60 cmH2O/(L/s)
}

export interface VentilationInput {
  squeezeVolumeMl: number; // Volume squeezed from BVM (0 to 1200 mL)
  squeezeDurationSec: number; // Time taken to deliver volume (normal ~1.0s)
  headTiltAngleDeg: number;
  jawThrustActive: boolean;
  currentGastricVolumeMl: number;
  currentSpO2: number;
  hasSpontaneousCirculation: boolean; // false during arrest
}

export interface VentilationResult {
  airwayState: AirwayState;
  pulmonaryVolumeMl: number; // Air entering lungs
  gastricVolumeMl: number; // Air diverted to stomach
  totalGastricAccumulationMl: number; // Cumulative gastric volume
  peakInspiratoryPressureCmH2O: number;
  chestRisePercentage: number; // 0 to 100% visible excursion
  spO2AfterBreath: number; // 0 to 100%
  clinicalFeedback: {
    status: 'optimal' | 'hypoventilation' | 'hyperventilation' | 'gastric_distension' | 'occluded';
    message: string;
    warning?: string;
  };
}

/**
 * Evaluates airway patency based on head-tilt / chin-lift angle and jaw thrust.
 */
export function evaluateAirwayPatency(headTiltAngleDeg: number, jawThrustActive: boolean): AirwayState {
  const effectiveTilt = Math.max(0, Math.min(50, headTiltAngleDeg));
  
  // Jaw thrust immediately opens airway even with minimal neck tilt (trauma-safe)
  const isAirwayOpen = jawThrustActive || effectiveTilt >= 25;

  let airwayResistanceCmH2O: number;
  if (jawThrustActive) {
    airwayResistanceCmH2O = 3.0;
  } else if (effectiveTilt >= 30) {
    // Fully aligned pharyngeal axis
    airwayResistanceCmH2O = 2.5 + (35 - Math.min(35, effectiveTilt)) * 0.2;
  } else if (effectiveTilt >= 20) {
    // Partially occluded
    airwayResistanceCmH2O = 12.0 + (30 - effectiveTilt) * 2.5;
  } else {
    // Posterior pharyngeal tongue collapse
    airwayResistanceCmH2O = 45.0 + (20 - effectiveTilt) * 1.5;
  }

  return {
    headTiltAngleDeg: effectiveTilt,
    jawThrustActive,
    isAirwayOpen,
    airwayResistanceCmH2O,
  };
}

/**
 * Calculates BVM delivery outcome, partitioning airflow between pulmonary
 * alveolar expansion and esophageal gastric insufflation based on lower
 * esophageal sphincter (LES) opening threshold (~20 cmH2O).
 */
export function calculateBVMVentilation(input: VentilationInput): VentilationResult {
  const airway = evaluateAirwayPatency(input.headTiltAngleDeg, input.jawThrustActive);
  const flowRateLPerSec = (input.squeezeVolumeMl / 1000) / Math.max(0.2, input.squeezeDurationSec);
  
  // Lung compliance: normal adult ~ 0.05 L/cmH2O (50 mL/cmH2O)
  // Gastric distension decreases lung compliance by elevating the diaphragm
  const gastricImpairment = Math.min(0.5, (input.currentGastricVolumeMl / 800) * 0.3);
  const lungComplianceLPerCmH2O = Math.max(0.02, 0.05 - gastricImpairment);

  // Peak Inspiratory Pressure: P_peak = (V / C) + (Flow * R)
  const resistivePressure = flowRateLPerSec * airway.airwayResistanceCmH2O;
  
  let pulmonaryVolumeMl = 0;
  let gastricVolumeMl = 0;

  // Lower Esophageal Sphincter opening pressure: ~20 cmH2O
  const LES_OPENING_PRESSURE = 20.0;

  if (!airway.isAirwayOpen) {
    // Occluded airway: High resistance prevents lung filling;
    // air forces open the esophagus into the stomach.
    gastricVolumeMl = input.squeezeVolumeMl * 0.85;
    pulmonaryVolumeMl = input.squeezeVolumeMl * 0.15;
  } else {
    // Airway is open
    if (input.squeezeVolumeMl <= 650 && input.squeezeDurationSec >= 0.8) {
      // Gentle 1.0s squeeze in target 500-600 mL window: virtually 100% to lungs
      pulmonaryVolumeMl = input.squeezeVolumeMl * 0.96;
      gastricVolumeMl = input.squeezeVolumeMl * 0.04;
    } else {
      // High flow or excessive volume exceeds LES pressure threshold
      const estimatedPeakP = (input.squeezeVolumeMl / 1000 / lungComplianceLPerCmH2O) + resistivePressure;
      if (estimatedPeakP > LES_OPENING_PRESSURE) {
        const excessFraction = Math.min(0.6, (estimatedPeakP - LES_OPENING_PRESSURE) / 25.0);
        gastricVolumeMl = input.squeezeVolumeMl * excessFraction;
        pulmonaryVolumeMl = input.squeezeVolumeMl * (1 - excessFraction);
      } else {
        pulmonaryVolumeMl = input.squeezeVolumeMl * 0.95;
        gastricVolumeMl = input.squeezeVolumeMl * 0.05;
      }
    }
  }

  // Calculate Peak Inspiratory Pressure generated by BVM squeeze
  const peakInspiratoryPressureCmH2O = (input.squeezeVolumeMl / 1000 / lungComplianceLPerCmH2O) + resistivePressure;
  
  // Chest rise percentage (500-600 mL corresponds to ~85-100% visible rise)
  const chestRisePercentage = Math.min(100, Math.round((pulmonaryVolumeMl / 550) * 100));

  const totalGastricAccumulationMl = input.currentGastricVolumeMl + gastricVolumeMl;

  // SpO2 dynamic response:
  // An effective breath adds oxygen to alveolar spaces.
  let spO2AfterBreath = input.currentSpO2;
  if (pulmonaryVolumeMl >= 400) {
    const oxygenBoost = (pulmonaryVolumeMl / 600) * 6.0; // +4-6% boost per good breath
    spO2AfterBreath = Math.min(99, input.currentSpO2 + oxygenBoost);
  } else {
    // Insufficient volume
    spO2AfterBreath = Math.max(50, input.currentSpO2 - 1.0);
  }

  // Clinical feedback determination
  let status: VentilationResult['clinicalFeedback']['status'];
  let message: string;
  let warning: string | undefined;

  if (!airway.isAirwayOpen) {
    status = 'occluded';
    message = 'Airway occluded! Tongue is blocking posterior pharynx.';
    warning = 'Perform Head-Tilt / Chin-Lift or Jaw-Thrust before squeezing BVM!';
  } else if (pulmonaryVolumeMl > 650 || input.squeezeDurationSec < 0.8 || input.squeezeVolumeMl > 750) {
    status = 'hyperventilation';
    message = 'Breath given too forcefully or too fast.';
    warning = 'Excessive intrathoracic pressure reduces venous return and cardiac output!';
  } else if (totalGastricAccumulationMl >= 300) {
    status = 'gastric_distension';
    message = 'Severe gastric distension! Stomach inflated with air.';
    warning = 'High risk of regurgitation and pulmonary aspiration! Ventilate gently over 1 second.';
  } else if (pulmonaryVolumeMl < 400) {
    status = 'hypoventilation';
    message = 'Inadequate tidal volume delivered (< 400 mL).';
    warning = 'Chest rise insufficient to oxygenate vital organs.';
  } else {
    status = 'optimal';
    message = `✓ Optimal Ventilation: ${Math.round(pulmonaryVolumeMl)} mL delivered over ${input.squeezeDurationSec.toFixed(1)}s.`;
  }

  return {
    airwayState: airway,
    pulmonaryVolumeMl: Math.round(pulmonaryVolumeMl),
    gastricVolumeMl: Math.round(gastricVolumeMl),
    totalGastricAccumulationMl: Math.round(totalGastricAccumulationMl),
    peakInspiratoryPressureCmH2O: parseFloat(peakInspiratoryPressureCmH2O.toFixed(1)),
    chestRisePercentage,
    spO2AfterBreath: Math.round(spO2AfterBreath),
    clinicalFeedback: {
      status,
      message,
      warning,
    },
  };
}
