import { AssessmentQuestion } from './residentialQuestions';

export const INDUSTRIAL_QUESTIONS: AssessmentQuestion[] = [
  // INDUSTRIAL ELECTRICIAN & TECHNICIAN (1-30)
  {
    id: 101,
    question: "What is the very FIRST step before performing maintenance on a 415V 3-phase industrial motor?",
    options: ["Verify Lockout/Tagout (LOTO) and zero-energy state with a calibrated multimeter", "Start unscrewing junction box bolts immediately", "Wipe the motor housing with a damp rag", "Turn off room light switches"],
    correctAnswer: 0,
    explanation: "Lockout/Tagout (LOTO) and testing with a rated multimeter verifies zero electrical energy before opening live enclosures.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 102,
    question: "What is an Arc Flash hazard in industrial switchgear?",
    options: ["A flash of light from low battery LED indicators", "An explosive release of heat, light, and pressure caused by an electric arc fault across air", "A harmless static spark when touching door handles", "A light signal showing motor rotation"],
    correctAnswer: 1,
    explanation: "Arc flashes produce temperatures up to 35,000°F (19,400°C), vaporizing copper and generating lethal blast pressures.",
    targetProfiles: ["electrician", "engineer", "technician", "supervisor", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 103,
    question: "What rating must safety glasses have when working inside an industrial Arc Flash Boundary?",
    options: ["Standard tinted sunglasses", "ANSI Z87.1 approved with side shields and arc-rated face protection", "Reading glasses", "Swimming goggles"],
    correctAnswer: 1,
    explanation: "Arc flash face shields and ANSI Z87.1 side-shield safety glasses protect eyes from intense UV radiation and flying debris.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "PPE Selection"
  },
  {
    id: 104,
    question: "What is the purpose of testing Voltage Rated Gloves for air leaks before each work shift?",
    options: ["To make them feel softer", "To detect pinhole leaks that allow high-voltage current to puncture the rubber layer", "To clean out dust", "To stretch glove fingers"],
    correctAnswer: 1,
    explanation: "Roll-testing or using an air inflator checks for microscopic pinholes that break dielectric resistance under high voltage.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "PPE Selection"
  },
  {
    id: 105,
    question: "What category rating (CAT rating) multimeter is required for 480V industrial main distribution panels?",
    options: ["CAT I (Electronic devices)", "CAT IV 600V or CAT III 1000V rated meter and leads", "Any cheap pocket meter", "12V automotive test light"],
    correctAnswer: 1,
    explanation: "CAT III and CAT IV meters withstand high-energy transient voltage surges occurring on main industrial utility feeders.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "Testing & Meters"
  },
  {
    id: 106,
    question: "Why must leather protector gloves be worn OVER rubber insulating voltage gloves?",
    options: ["To keep rubber gloves warm", "To protect the delicate rubber from punctures, abrasions, and chemical damage", "To improve color matching", "To add extra thickness for grip"],
    correctAnswer: 1,
    explanation: "Rubber insulating gloves provide dielectric protection, while leather protectors shield the rubber from sharp metal cuts.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "PPE Selection"
  },
  {
    id: 107,
    question: "What is 'Step Potential' near a grounded high-voltage power line touching the earth?",
    options: ["The distance you step when climbing stairs", "The dangerous voltage difference between your feet as you walk across energized ground", "The energy generated by foot steps", "The height of a transformer pad"],
    correctAnswer: 1,
    explanation: "Fault current flowing into earth creates concentric voltage rings. Taking long steps creates high voltage across your legs.",
    targetProfiles: ["electrician", "engineer", "supervisor", "all"],
    category: "Grounding Hazards"
  },
  {
    id: 108,
    question: "How should a technician safely exit a high-voltage substation ground fault area experiencing Step Potential?",
    options: ["Run fast with wide strides", "Shuffle feet together without lifting them from the ground until clear of the boundary", "Crawl on hands and knees", "Hop on one foot"],
    correctAnswer: 1,
    explanation: "Shuffling or hopping with feet tightly together keeps both feet at the exact same potential, eliminating body current path.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "Grounding Hazards"
  },
  {
    id: 109,
    question: "What is the NFPA 70E 'Limited Approach Boundary'?",
    options: ["The border of the company parking lot", "An approach boundary to protect unqualified persons from shock hazards", "The distance to the cafeteria", "The fence around solar panels"],
    correctAnswer: 1,
    explanation: "The Limited Approach Boundary sets a distance barrier that unqualified personnel must not cross without qualified escorts.",
    targetProfiles: ["supervisor", "engineer", "electrician", "all"],
    category: "Safety Boundaries"
  },
  {
    id: 110,
    question: "What does an Arc Flash Warning Label on a circuit panel specify?",
    options: ["Nominal system voltage, incident energy rating, arc flash boundary, and required PPE category", "The manufacturer logo only", "The price of the cabinet", "The painter's signature"],
    correctAnswer: 0,
    explanation: "Arc Flash labels state incident energy in cal/cm², safe working distance, boundaries, and required arc-rated clothing.",
    targetProfiles: ["engineer", "supervisor", "electrician", "technician", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 111,
    question: "What does the NFPA 70E 'Three-Point Test' method for voltage verification require?",
    options: ["Test meter on known live source, test target circuit, re-test meter on known live source", "Test three different phase wires at once", "Measure voltage three times in one second", "Ask three coworkers for opinions"],
    correctAnswer: 0,
    explanation: "Proving your meter works before AND after probing the target circuit guarantees a zero reading is not a blown meter fuse.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Testing & Meters"
  },
  {
    id: 112,
    question: "Why should synthetic polyester or nylon clothing NEVER be worn under arc flash suits?",
    options: ["Synthetic fabrics are too cold", "Synthetic fibers melt into human skin during arc flash heat, causing severe third-degree burns", "Synthetics stretch easily", "Synthetics absorb motor oil"],
    correctAnswer: 1,
    explanation: "Unrated synthetic materials melt at low temperatures, fusing molten plastic directly into burn wounds during arc flashes.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "PPE Selection"
  },
  {
    id: 113,
    question: "What is the primary function of a portable Safety Grounding Cluster applied to de-energized high-voltage lines?",
    options: ["To supply backup power to tools", "To create a solid low-resistance short circuit to ground, tripping breakers if lines re-energize", "To hold cables in place", "To prevent rust on conductors"],
    correctAnswer: 1,
    explanation: "Temporary protective grounding clamps ensure zero voltage potential and trip upstream breakers if accidentally powered.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "Grounding Hazards"
  },
  {
    id: 114,
    question: "Who is authorized to remove a personal Lockout/Tagout (LOTO) padlock from an industrial breaker?",
    options: ["Any worker on shift", "ONLY the person who placed the lock, except under strict emergency supervisor override procedures", "The janitor", "The machine operator"],
    correctAnswer: 1,
    explanation: "LOTO integrity requires individual control. Only the lock owner may remove their lock after completing work safely.",
    targetProfiles: ["supervisor", "electrician", "technician", "engineer", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 115,
    question: "Why must industrial power factor correction capacitors be grounded and discharged before servicing?",
    options: ["Capacitors collect moisture", "Capacitors store dangerous electrical charge long after the main power is disconnected", "Capacitors rust inside", "Capacitors lose magnetic field"],
    correctAnswer: 1,
    explanation: "High-voltage capacitors act as electrical storage tanks. Touching charged capacitors delivers lethal shocks.",
    targetProfiles: ["electrician", "engineer", "technician", "all"],
    category: "Capacitor & High V"
  },
  {
    id: 116,
    question: "What is the minimum safe clearance distance from energized 11kV overhead lines for non-electrical equipment?",
    options: ["1 foot (0.3m)", "10 feet (3.0m) plus additional distance for higher voltages", "2 inches", "No distance needed"],
    correctAnswer: 1,
    explanation: "OSHA mandates a minimum 10-foot radial clearance for equipment working near overhead power lines up to 50kV.",
    targetProfiles: ["supervisor", "engineer", "technician", "all"],
    category: "Safety Boundaries"
  },
  {
    id: 117,
    question: "What is 'Touch Potential' hazard in high-voltage substations?",
    options: ["Touching a computer screen", "Voltage difference between an energized metal structure touched by hand and the ground under foot", "Static electricity from carpet", "Touching rubber gloves"],
    correctAnswer: 1,
    explanation: "If a faulted metallic frame is energized, touching it while standing on ground causes current to pass through arms and chest.",
    targetProfiles: ["engineer", "electrician", "technician", "all"],
    category: "Grounding Hazards"
  },
  {
    id: 118,
    question: "What is the purpose of an Emergency Stop (E-Stop) push button on an industrial conveyor belt?",
    options: ["To pause production for lunch break", "To immediately cut control power and bring machinery to a fast, safe emergency shutdown", "To reverse conveyor direction", "To sound factory shift horn"],
    correctAnswer: 1,
    explanation: "E-Stops override all operational commands to halt hazardous machine motion instantly during emergency events.",
    targetProfiles: ["technician", "supervisor", "electrician", "all"],
    category: "Controls & E-Stop"
  },
  {
    id: 119,
    question: "What rating class of insulating rubber gloves is required for working on 4,160V medium voltage systems?",
    options: ["Class 00 (Max 500V)", "Class 1 (Max 7,500V)", "Class 0 (Max 1,000V)", "Household dishwashing gloves"],
    correctAnswer: 1,
    explanation: "Class 1 rubber insulating gloves are proof-tested to 10,000V AC and rated for maximum use voltage up to 7,500V AC.",
    targetProfiles: ["electrician", "engineer", "all"],
    category: "PPE Selection"
  },
  {
    id: 20,
    question: "Why are insulated hand tools (rated 1000V VDE/IEC 60900) required when working inside energized switchboards?",
    options: ["Insulated handles make tools heavier", "Special dual-layer insulation prevents accidental phase-to-phase or phase-to-ground short circuits", "Insulation prevents metal rust", "Tool handles look professional"],
    correctAnswer: 1,
    explanation: "VDE insulated tools prevent bare metal shafts from touching adjacent live busbars, stopping catastrophic arc faults.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Tool Safety"
  },

  // INDUSTRIAL ENGINEERING & SUPERVISION (121-160)
  {
    id: 121,
    question: "What is the main goal of a Hazardous Electrical Energy Control Program (LOTO)?",
    options: ["To prevent equipment theft", "To prevent unexpected machine startup or release of stored energy during service work", "To speed up factory throughput", "To cut electricity bills"],
    correctAnswer: 1,
    explanation: "OSHA 1910.147 outlines LOTO requirements to protect workers from unexpected energy release during repair tasks.",
    targetProfiles: ["supervisor", "engineer", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 122,
    question: "What does an Insulation Resistance Tester (Megohmmeter / 'Megger') measure?",
    options: ["Battery voltage", "High-resistance integrity of cable and motor winding insulation in Mega-Ohms", "Current flow in Amps", "Grid frequency"],
    correctAnswer: 1,
    explanation: "Megohmmeters apply high DC voltage (500V-5000V) to detect breakdown, moisture, and degradation in wire insulation.",
    targetProfiles: ["engineer", "electrician", "technician", "all"],
    category: "Testing & Meters"
  },
  {
    id: 123,
    question: "What is an Arc Flash Boundary distance calculated using IEEE 1584 standards?",
    options: ["The distance to the building exit", "The distance from an arc source where incident energy drops to 1.2 cal/cm² (onset of 2nd degree burn)", "The length of the power cable", "The height of the transformer"],
    correctAnswer: 1,
    explanation: "At 1.2 cal/cm², bare skin suffers second-degree burns. Anyone inside this boundary must wear arc-rated PPE.",
    targetProfiles: ["engineer", "supervisor", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 124,
    question: "Why should Current Transformers (CTs) secondary terminals NEVER be opened while primary current is flowing?",
    options: ["The secondary wire will turn blue", "Open-circuiting a CT secondary produces dangerously high induced voltage spikes that explode CTs and shock technicians!", "The motor turns off", "Current flows backwards"],
    correctAnswer: 1,
    explanation: "CTs act as step-up transformers when open-circuited, generating thousands of Volts across open secondary leads.",
    targetProfiles: ["engineer", "electrician", "technician", "all"],
    category: "Transformer Safety"
  },
  {
    id: 125,
    question: "What is the function of a Ground Fault Protection Relay (GFR) in industrial switchgear?",
    options: ["To regulate room temperature", "To trip main breakers when low-level leakage current to ground is detected, preventing fires and shocks", "To boost motor horsepower", "To record energy meters"],
    correctAnswer: 1,
    explanation: "GFR relays monitor zero-sequence current balance and trip breakers before ground faults escalate into arc flash blasts.",
    targetProfiles: ["engineer", "supervisor", "all"],
    category: "System Protection"
  },
  {
    id: 126,
    question: "What is 'Zero Energy Verification' in Lockout/Tagout safety?",
    options: ["Checking if electric bills are zero", "Testing all electrical, hydraulic, pneumatic, and mechanical energy sources to confirm absolute zero energy state", "Turning off the main lights", "Removing all fuse covers"],
    correctAnswer: 1,
    explanation: "Zero energy verification tests for residual voltage, stored springs, compressed air, and hydraulic pressure before work begins.",
    targetProfiles: ["supervisor", "electrician", "technician", "engineer", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 127,
    question: "What type of ladder must be used for electrical maintenance in industrial facilities?",
    options: ["Aluminum extension ladder", "Non-conductive Fiberglass or heavy dry wood ladder", "Steel scaffolding ladder", "Iron step stool"],
    correctAnswer: 1,
    explanation: "Fiberglass side rails prevent the ladder from becoming a conductive short-circuit path to ground if live wires are brushed.",
    targetProfiles: ["technician", "electrician", "supervisor", "all"],
    category: "Safety Boundaries"
  },
  {
    id: 128,
    question: "What is the primary danger of opening an air-break disconnect switch under heavy electrical load?",
    options: ["The switch handle is heavy", "A violent electric arc forms across contacts, causing arc blast explosions and severe burns!", "The switch makes a clicking noise", "It turns off the room fan"],
    correctAnswer: 1,
    explanation: "Non-load-break disconnect switches cannot extinguish load current arcs. Opening them under load creates massive arc flashes.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "Switching Safety"
  },
  {
    id: 129,
    question: "What is an Arc Flash Blast Pressure Wave?",
    options: ["A gust of cool air", "Extremely high air pressure generated by rapidly expanding superheated copper vapor and air during an arc fault", "Sound from motor fans", "Static shock wave"],
    correctAnswer: 1,
    explanation: "Arc blasts produce explosive pressures exceeding 2000 lbs/sq ft, blowing enclosure doors off hinges and rupturing eardrums.",
    targetProfiles: ["engineer", "supervisor", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 130,
    question: "Why must industrial work sites enforce a 'Two-Person Rule' for high-voltage maintenance?",
    options: ["To finish the work in half the time", "So a qualified standby person trained in CPR/First Aid can initiate emergency shutdown and rescue if a shock occurs", "To share heavy toolboxes", "For supervisor monitoring"],
    correctAnswer: 1,
    explanation: "The standby partner monitors safety boundaries, keeps unauthorized personnel clear, and provides immediate life support.",
    targetProfiles: ["supervisor", "engineer", "electrician", "all"],
    category: "Emergency & CPR"
  },

  // INDUSTRIAL SAFETY QUESTIONS (131-200)
  {
    id: 131,
    question: "What is the purpose of an Arc Reduction Maintenance System (ARMS) switch on circuit breakers?",
    options: ["To save electricity overnight", "To temporarily lower breaker trip delay times during maintenance, minimizing arc flash energy", "To increase motor torque", "To bypass LOTO locks"],
    correctAnswer: 1,
    explanation: "ARMS switches force instantaneous tripping during maintenance, drastically reducing potential arc flash incident energy.",
    targetProfiles: ["engineer", "electrician", "supervisor", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 132,
    question: "What is the purpose of a Grounding Resistance Monitor in an Ungrounded Industrial Delta grid?",
    options: ["To count motor revolutions", "To continuously monitor ground insulation resistance and alarm on the first ground fault", "To measure room temperature", "To adjust phase angles"],
    correctAnswer: 1,
    explanation: "Ungrounded grids can tolerate a single ground fault without tripping, but monitors warn operators before a second fault causes a phase-to-phase short.",
    targetProfiles: ["engineer", "electrician", "technician", "all"],
    category: "System Protection"
  },
  {
    id: 133,
    question: "What is the safe procedure when replacing high-voltage HRC (High Rupturing Capacity) fuses?",
    options: ["Use bare hands while energized", "De-energize circuit, verify zero voltage, and use insulated fuse pullers with PPE", "Use metal pliers while energized", "Wrap fuses in aluminum foil"],
    correctAnswer: 1,
    explanation: "HRC fuses protect heavy industrial circuits. Replacement requires isolation, voltage verification, and rated fuse pullers.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Fuses & Breakers"
  },
  {
    id: 134,
    question: "What is the function of a transformer Buchholz Relay?",
    options: ["To measure oil temperature only", "To detect gas accumulation and rapid oil surges caused by internal arc faults in oil-filled transformers", "To regulate secondary voltage", "To filter cooling fans"],
    correctAnswer: 1,
    explanation: "Buchholz relays sense gas bubbles generated by oil breakdown during internal transformer dielectric failures.",
    targetProfiles: ["engineer", "technician", "all"],
    category: "Transformer Safety"
  },
  {
    id: 135,
    question: "Why must static ground grounding clamps be attached to chemical tank trucks during flammable liquid transfer?",
    options: ["To support the hose weight", "To dissipate static electric charge buildup that could spark and ignite explosive chemical vapors", "To measure liquid volume", "To keep the truck level"],
    correctAnswer: 1,
    explanation: "Fluid flow generates high static voltage. Bonding clamps equalize potential to eliminate static spark ignition risks.",
    targetProfiles: ["supervisor", "engineer", "technician", "all"],
    category: "Hazardous Locations"
  },
  {
    id: 136,
    question: "What does Class I, Division 1 electrical equipment rating mean in industrial plants?",
    options: ["Suitable for office rooms", "Explosion-proof equipment designed for locations where flammable gases or vapors are continuously present", "Outdoor rainproof rating", "High efficiency motor rating"],
    correctAnswer: 1,
    explanation: "Class I Div 1 areas contain hazardous concentrations of flammable gases under normal operating conditions.",
    targetProfiles: ["engineer", "supervisor", "electrician", "all"],
    category: "Hazardous Locations"
  },
  {
    id: 137,
    question: "What is the purpose of Lockout Hasps in group LOTO procedures?",
    options: ["To hold extra keychains", "To allow multiple workers to place individual safety padlocks on a single energy isolation point", "To lock toolboxes shut", "To hang warning signs"],
    correctAnswer: 1,
    explanation: "Hasps feature 6 lock holes, ensuring the equipment cannot be powered up until every single worker removes their lock.",
    targetProfiles: ["supervisor", "electrician", "technician", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 138,
    question: "What is the danger of using ungrounded portable diesel generators on construction sites?",
    options: ["Fuel burns faster", "Ground faults in connected tools can energize generator metal frames and shock operators", "The generator runs too quiet", "Exhaust turns blue"],
    correctAnswer: 1,
    explanation: "Frame bonding and earth grounding rods provide low-resistance fault return paths to trip generator circuit breakers.",
    targetProfiles: ["technician", "supervisor", "all"],
    category: "Grounding Hazards"
  },
  {
    id: 139,
    question: "What is the hazard of opening an energized motor junction box without PPE?",
    options: ["Dust will enter the box", "Moisture or loose leads inside can trigger an immediate arc fault right in front of the technician's face", "The motor runs backward", "Wires get tangled"],
    correctAnswer: 1,
    explanation: "Vibration in motor terminal boxes can loosen connections, causing phase-to-phase arc faults upon opening.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 140,
    question: "What does an Infrared (IR) Thermography Inspection detect on electrical switchgear panels?",
    options: ["Panel paint thickness", "Abnormal hot spots caused by loose connections, overloaded phases, or corroded contacts", "Panel height alignment", "Internal sound levels"],
    correctAnswer: 1,
    explanation: "IR thermal cameras identify resistance heat buildup long before loose terminals melt insulation or ignite arc faults.",
    targetProfiles: ["engineer", "technician", "electrician", "all"],
    category: "Testing & Meters"
  },
  {
    id: 141,
    question: "Why should you never use metal measuring tapes near live busbars inside switchboards?",
    options: ["Metal tapes bend easily", "Flexible metal tape can bridge live busbars to ground, triggering catastrophic arc blasts", "Tapes scratch metal paint", "Rulers read incorrect inches"],
    correctAnswer: 1,
    explanation: "Conductive tape measures accidentally dropped onto busbars bridge phase gaps, causing instant arc explosions.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "Tool Safety"
  },
  {
    id: 142,
    question: "What is the function of a Ground Fault Interrupter (GFI) breaker in industrial construction temporary power panels?",
    options: ["To measure total power usage", "To trip power within 25ms if ground leakage current exceeds 4-6mA, protecting workers from shocks", "To regulate 60Hz frequency", "To power site radios"],
    correctAnswer: 1,
    explanation: "Class A GFCI protection on job sites prevents fatal electrocution from damaged power tools or wet cables.",
    targetProfiles: ["technician", "supervisor", "electrician", "all"],
    category: "System Protection"
  },
  {
    id: 143,
    question: "Why must high-voltage rubber gloves be stored in proper canvas storage bags away from sunlight?",
    options: ["Canvas bags make gloves look neat", "UV radiation, ozone, and heat degrade rubber polymers, causing microscopic cracks and loss of insulation", "To keep gloves secret", "To prevent dust accumulation only"],
    correctAnswer: 1,
    explanation: "Ozone and sunlight break down natural rubber bonds (ozone tracking), rendering insulating gloves unsafe.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "PPE Selection"
  },
  {
    id: 144,
    question: "What is the purpose of an Arc Flash Face Shield rating measured in cal/cm²?",
    options: ["To measure shield weight", "To indicate the maximum incident thermal energy the shield can withstand without thermal transfer or melting", "To gauge tint darkness", "To measure impact speed"],
    correctAnswer: 1,
    explanation: "Arc shields are rated (e.g. 12 cal/cm², 40 cal/cm²) to match the calculated incident energy level of the workspace.",
    targetProfiles: ["engineer", "electrician", "technician", "all"],
    category: "PPE Selection"
  },
  {
    id: 145,
    question: "What should you do if an industrial motor control cabinet smells strongly of burnt enamel wire?",
    options: ["Keep motor running to finish the work shift", "Stop motor, lock out power, and inspect stator windings for shorted turns", "Pour cooling water on cabinet", "Increase ventilation fan speed"],
    correctAnswer: 1,
    explanation: "Burnt enamel smell signals motor winding insulation breakdown. Continuing operation causes phase-to-ground faults.",
    targetProfiles: ["technician", "electrician", "supervisor", "all"],
    category: "Motors & Controls"
  },
  {
    id: 146,
    question: "What is the purpose of equipotential bonding in industrial facilities?",
    options: ["To join structural steel for strength", "To connect all conductive metallic parts so zero voltage difference exists between touched objects", "To improve Wi-Fi ground", "To save cable length"],
    correctAnswer: 1,
    explanation: "Bonding ensures all metal enclosures, pipes, and structures remain at identical electrical potential, eliminating shock paths.",
    targetProfiles: ["engineer", "electrician", "all"],
    category: "Grounding Hazards"
  },
  {
    id: 147,
    question: "Why are high-voltage power transformers equipped with pressure relief valves?",
    options: ["To release oil during overfill", "To safely vent extreme pressure buildup from oil vaporized by internal arc faults, preventing tank explosions", "To check oil level", "To cool internal windings"],
    correctAnswer: 1,
    explanation: "Internal transformer arcing rapidly vaporizes dielectric oil. Pressure relief valves discharge gas before steel tanks rupture.",
    targetProfiles: ["engineer", "technician", "all"],
    category: "Transformer Safety"
  },
  {
    id: 148,
    question: "What is the correct action if an industrial electrical fires breaks out near high-voltage switchgear?",
    options: ["Use high-pressure water hose", "Evacuate area, trip upstream main power if safe, and deploy CO2 / Clean Agent systems", "Throw sand on live switchgear", "Use foam fire extinguishers"],
    correctAnswer: 1,
    explanation: "CO2 and gas clean agents extinguish electrical fires without conducting current or leaving corrosive residue on live parts.",
    targetProfiles: ["supervisor", "electrician", "engineer", "all"],
    category: "Emergency & CPR"
  },
  {
    id: 149,
    question: "What is the minimum working clearance required in front of 480V industrial control panels (OSHA 1910.303)?",
    options: ["1 foot (0.3m)", "3 feet (0.9m) minimum clear depth with 30-inch width", "6 inches", "No clearance required"],
    correctAnswer: 1,
    explanation: "OSHA requires clear working space of at least 3 feet deep in front of live equipment to allow safe movement and quick escape.",
    targetProfiles: ["supervisor", "engineer", "electrician", "all"],
    category: "Safety Boundaries"
  },
  {
    id: 150,
    question: "What is the hazard of working on DC solar array strings high voltage disconnects?",
    options: ["DC power turns off at night", "DC arcs do not have zero-voltage crossings, making DC arcs harder to extinguish and prone to sustained arcing!", "Solar panels store magnetic energy", "DC current vibrates wires"],
    correctAnswer: 1,
    explanation: "Unlike AC current which crosses zero 100-120 times a second, DC current flows continuously, sustaining severe long-duration arcs.",
    targetProfiles: ["engineer", "electrician", "technician", "all"],
    category: "Solar & DC Safety"
  },

  // FINAL INDUSTRIAL SCENARIOS (151-200)
  {
    id: 151,
    question: "What is the function of a Phase Rotation Meter when connecting 3-phase industrial equipment?",
    options: ["To measure voltage magnitude", "To verify correct A-B-C phase sequence so motors rotate in the correct direction", "To test line frequency", "To balance single phase loads"],
    correctAnswer: 1,
    explanation: "Reversing phase rotation causes 3-phase motors, pumps, and compressors to spin backwards, damaging machinery.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Testing & Meters"
  },
  {
    id: 152,
    question: "Why should compressed air never be used to blow copper dust out of live switchboards?",
    options: ["Air makes too much noise", "Air blasts scatter conductive copper dust into live insulating gaps, causing phase short circuits!", "Dust ruins air nozzles", "It blows away wire labels"],
    correctAnswer: 1,
    explanation: "Blowing metallic dust creates conductive airborne clouds that bridge phase insulation, causing catastrophic arc faults.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Maintenance Safety"
  },
  {
    id: 153,
    question: "What does 'NFPA 70E Standard for Electrical Safety in the Workplace' regulate?",
    options: ["Building elevator speeds", "Electrical safety requirements, LOTO procedures, PPE, and arc flash protection for workers", "Plumbing pipe sizes", "Fire sprinkler water flow"],
    correctAnswer: 1,
    explanation: "NFPA 70E is the premier standard establishing safe work practices to protect personnel from electrical hazards.",
    targetProfiles: ["supervisor", "engineer", "all"],
    category: "Safety Boundaries"
  },
  {
    id: 154,
    question: "Why must insulated tools be visually inspected for cracks in the orange/yellow outer layer before use?",
    options: ["To keep tools shiny", "Damaged insulation layers allow voltage to bypass the tool guard into the technician's hand", "To check brand logo", "To balance tool weight"],
    correctAnswer: 1,
    explanation: "Dual-color VDE insulation uses contrasting inner layers (e.g. yellow under orange) to signal insulation damage.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Tool Safety"
  },
  {
    id: 155,
    question: "What is the purpose of an Arc Flash Hood / Bee-keeper helmet during Category 4 electrical operations?",
    options: ["To keep out mosquitoes", "To provide 360-degree head, neck, and face protection against intense thermal radiation and arc blasts", "To look like an astronaut", "To reduce room sound"],
    correctAnswer: 1,
    explanation: "Full arc hoods with arc-rated face shields shield head, neck, and throat areas from lethal convective heat.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "PPE Selection"
  },
  {
    id: 156,
    question: "What is the danger of using a multimeter set to CURRENT (Amps) mode across a live voltage line?",
    options: ["The meter screen turns dim", "Current mode has nearly zero internal resistance, creating a direct dead SHORT CIRCUIT that explodes meter fuses!", "The battery drains", "Voltage reads zero"],
    correctAnswer: 1,
    explanation: "Ammeter jacks act as solid short circuits. Placing ammeter leads across voltage lines causes explosive short-circuit arc flashes inside the meter.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "Testing & Meters"
  },
  {
    id: 157,
    question: "What is the purpose of a LOTO Lockout Box (Group Lockbox)?",
    options: ["To store spare keys", "Keys to primary equipment locks are placed inside the box, and each team member places their lock on the box handle", "To ship locks between factories", "To lock up user cell phones"],
    correctAnswer: 1,
    explanation: "Group LOTO boxes ensure the primary key cannot be accessed to energize equipment until every worker removes their padlock.",
    targetProfiles: ["supervisor", "engineer", "electrician", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 158,
    question: "What should you do if an industrial transformer tank is bulging and leaking hot oil?",
    options: ["Climb on top to inspect oil cap", "Evacuate immediate area, establish safety perimeter, and de-energize transformer remotely", "Wipe oil with cotton rags while live", "Pour cold water on tank"],
    correctAnswer: 1,
    explanation: "Bulging transformer tanks signal internal arcing and extreme pressure buildup that can cause catastrophic tank explosion.",
    targetProfiles: ["engineer", "supervisor", "electrician", "all"],
    category: "Transformer Safety"
  },
  {
    id: 159,
    question: "Why should electrical maintenance technicians avoid wearing metal ring jewelry, watches, or metal belt buckles?",
    options: ["Metal rings scratch paint", "Metal jewelry acts as low-resistance conductors that melt during shorts, causing severe finger amputation burns!", "Jewelry catches on clothes", "Watches lose time"],
    correctAnswer: 1,
    explanation: "Metal rings touching live parts short circuit phases instantly, vaporizing metal and causing severe arc burn injuries.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "PPE Selection"
  },
  {
    id: 160,
    question: "What is the function of a Ground Fault Circuit Interrupter (GFCI) in damp industrial washdown zones?",
    options: ["To boost water pressure", "To cut power within 25 milliseconds when current leakage to ground exceeds 5mA", "To turn on wash lamps", "To clean motor casings"],
    correctAnswer: 1,
    explanation: "GFCIs constantly measure line and neutral current balance, isolating power before shock current reaches lethal levels.",
    targetProfiles: ["technician", "electrician", "all"],
    category: "System Protection"
  },
  {
    id: 161,
    question: "What is the primary cause of industrial electrical Arc Flash accidents?",
    options: ["High humidity only", "Accidental tool drops, dust accumulation, insulation failure, or touching live busbars", "Sunlight on panels", "Low line voltage"],
    correctAnswer: 1,
    explanation: "Over 75% of arc flashes are caused by human error (dropping metal tools) or conductive dust bridging live phase conductors.",
    targetProfiles: ["engineer", "supervisor", "electrician", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 162,
    question: "What does the term 'Qualified Person' mean under NFPA 70E guidelines?",
    options: ["Anyone wearing a hard hat", "A person trained and knowledgeable in electrical installation, hazard identification, and PPE usage", "A factory manager with a diploma", "A visitor with a safety badge"],
    correctAnswer: 1,
    explanation: "A Qualified Person has specific technical training to distinguish live parts, assess risk, and execute safety controls.",
    targetProfiles: ["supervisor", "engineer", "electrician", "all"],
    category: "Safety Boundaries"
  },
  {
    id: 163,
    question: "Why must de-energized high-voltage overhead lines be grounded on BOTH sides of a work area?",
    options: ["To make wires hang straight", "To protect workers from induced voltages from adjacent live lines and unexpected re-energization from either direction", "To measure line resistance", "To anchor wooden poles"],
    correctAnswer: 1,
    explanation: "Dual grounding creates an equipotential zone around workers, shielding them from electromagnetic induction and double-ended feeds.",
    targetProfiles: ["engineer", "electrician", "all"],
    category: "Grounding Hazards"
  },
  {
    id: 164,
    question: "What is the hazard of working inside an unventilated battery room containing lead-acid batteries?",
    options: ["Low oxygen levels only", "Charging lead-acid batteries emit explosive Hydrogen gas that can ignite from a single spark!", "Battery acid smells sweet", "Room gets too dark"],
    correctAnswer: 1,
    explanation: "Off-gassing during battery charging generates flammable hydrogen gas. Battery rooms require explosive-proof exhaust ventilation.",
    targetProfiles: ["technician", "electrician", "supervisor", "all"],
    category: "Hazardous Locations"
  },
  {
    id: 165,
    question: "What is the purpose of an Electrical Safety Permit (Energized Electrical Work Permit)?",
    options: ["To request extra overtime pay", "A formal authorization process documenting why live work is necessary, hazards, boundaries, and required PPE", "A parking pass for site trucks", "A badge for factory tours"],
    correctAnswer: 1,
    explanation: "Energized Work Permits ensure live work is performed only when de-energizing creates greater hazard or is physically infeasible.",
    targetProfiles: ["supervisor", "engineer", "all"],
    category: "Safety Boundaries"
  },
  {
    id: 166,
    question: "Why should rubber insulating gloves be stored inside out never?",
    options: ["It makes gloves look backwards", "Turning rubber inside out places high mechanical stress on folds, cracking the dielectric material", "Gloves get dirty inside", "It changes glove size"],
    correctAnswer: 1,
    explanation: "Inverting rubber gloves strains polymer bonds, creating microscopic stress fractures that fail under high voltage.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "PPE Selection"
  },
  {
    id: 167,
    question: "What is the purpose of a Snubber Circuit across industrial relay contactors?",
    options: ["To slow down relay speed", "To suppress inductive voltage spikes (back-EMF) and arcing when switching heavy motor loads", "To illuminate relay casing", "To reduce relay weight"],
    correctAnswer: 1,
    explanation: "RC snubbers absorb high voltage transients generated when breaking inductive motor currents, extending contact life.",
    targetProfiles: ["engineer", "technician", "all"],
    category: "Motors & Controls"
  },
  {
    id: 168,
    question: "What is the correct action if an electric shock victim is lying unconscious on a 480V live floor panel?",
    options: ["Grab victim's arms to drag them clear", "De-energize main circuit breaker immediately or use an insulated non-conductive rescue hook to pull victim clear", "Pour water on victim to revive", "Wait for ambulance without shutting power"],
    correctAnswer: 1,
    explanation: "Never touch a live shock victim with bare hands! Disconnect power or use rated hot sticks / rescue hooks.",
    targetProfiles: ["supervisor", "electrician", "technician", "engineer", "all"],
    category: "Emergency & CPR"
  },
  {
    id: 169,
    question: "What is the function of a Motor Thermal Overload Relay?",
    options: ["To measure motor speed", "To detect sustained over-current heat accumulation in motor windings and trip contactors before insulation burns", "To start the motor fan", "To measure grid voltage"],
    correctAnswer: 1,
    explanation: "Overload relays mirror motor thermal curves, interrupting control circuits when prolonged current causes motor overheating.",
    targetProfiles: ["technician", "electrician", "all"],
    category: "Motors & Controls"
  },
  {
    id: 170,
    question: "What is the hazard of resetting a tripped industrial breaker multiple times without investigating the cause?",
    options: ["The breaker lever gets loose", "Repeatedly closing into an un-cleared short circuit can cause violent breaker explosion and arc flash!", "It wastes electricity", "The panel paint turns dark"],
    correctAnswer: 1,
    explanation: "Breakers closing into high-fault currents suffer severe contact erosion and explosive pressure failure. Always diagnose first!",
    targetProfiles: ["supervisor", "electrician", "technician", "engineer", "all"],
    category: "Fuses & Breakers"
  },
  {
    id: 171,
    question: "What is the function of a Cable Shield (Screen) on Medium Voltage 11kV cables?",
    options: ["To add color identification", "To equalize electric field stress radially around the conductor and safely carry ground fault currents", "To make cables stiff", "To block water completely"],
    correctAnswer: 1,
    explanation: "Metallic cable shielding controls voltage stress concentration and provides a metallic return path for ground fault protection.",
    targetProfiles: ["engineer", "electrician", "all"],
    category: "System Protection"
  },
  {
    id: 172,
    question: "Why must safety locks in LOTO procedures be uniquely keyed with ONE key per lock?",
    options: ["Master keys are too expensive", "Uniquely keyed locks guarantee that no other worker can accidentally remove your safety lock", "Keys get lost easily", "Locksmiths recommend it"],
    correctAnswer: 1,
    explanation: "One worker, one lock, one key is the foundational safety rule preventing unauthorized lock removal.",
    targetProfiles: ["supervisor", "electrician", "technician", "engineer", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 173,
    question: "What does the NFPA 70E 'Prohibited Approach Boundary' signify?",
    options: ["The entrance gate of the facility", "The boundary where work is considered equivalent to making direct contact with live electrical parts", "The boundary for forklifts", "The office zone"],
    correctAnswer: 1,
    explanation: "Crossing the Prohibited Approach Boundary requires the same PPE and tools as direct physical contact with energized conductors.",
    targetProfiles: ["engineer", "electrician", "all"],
    category: "Safety Boundaries"
  },
  {
    id: 174,
    question: "What is the hazard of performing high-voltage cable insulation testing without discharging residual capacitance?",
    options: ["Cable gets cold", "Tested cables act like giant capacitors storing high DC voltage that shocks technicians after the test!", "Megger screen turns off", "Wire insulation turns hard"],
    correctAnswer: 1,
    explanation: "Long MV cables hold capacitive charge after Megger testing. Cables must be grounded for 4x test duration before touching.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "Testing & Meters"
  },
  {
    id: 175,
    question: "What is the purpose of an Arc Flash Blanket?",
    options: ["To keep workers warm in winter", "To contain potential arc flash blasts and deflect molten metal debris when working near live parts", "To cover dusty panels", "To absorb oil leaks"],
    correctAnswer: 1,
    explanation: "Kevlar arc blankets are rated to suppress and deflect explosive energy away from technicians during high-risk switching operations.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "PPE Selection"
  },
  {
    id: 176,
    question: "Why should oil-filled transformers have oil samples tested annually for Dissolved Gas Analysis (DGA)?",
    options: ["To check oil clarity", "DGA detects trace combustible gases created by internal incipient arcing, overheating, and insulation degradation", "To check oil smell", "To adjust oil viscosity"],
    correctAnswer: 1,
    explanation: "Dissolved Gas Analysis identifies early internal faults (acetylene, hydrogen, methane) months before catastrophic failure.",
    targetProfiles: ["engineer", "technician", "all"],
    category: "Transformer Safety"
  },
  {
    id: 177,
    question: "What is the safe procedure when racking out a Medium Voltage Vacuum Circuit Breaker?",
    options: ["Stand directly in front of the door without PPE", "Wear full arc flash PPE, stand to the side of the cubicle, and use remote racking tools if available", "Rack it out while motor is running", "Use a metal crowbar"],
    correctAnswer: 1,
    explanation: "Racking breakers carries elevated arc flash risk. Remote racking mechanisms allow operators to rack breakers from outside the boundary.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "Switching Safety"
  },
  {
    id: 178,
    question: "What does an Electrical Lockout Tag specify?",
    options: ["The price of the lock", "The name of the worker, date, department, reason for lockout, and emergency phone contact", "The factory address", "The serial number of the machine"],
    correctAnswer: 1,
    explanation: "LOTO tags clearly identify who isolated the power and why, warning everyone not to operate the control.",
    targetProfiles: ["supervisor", "electrician", "technician", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 179,
    question: "Why must variable frequency drives (VFDs) have a mandatory wait time (e.g. 5 minutes) after power off before opening covers?",
    options: ["To let cooling fans stop", "High-voltage DC bus capacitors inside VFDs take several minutes to safely discharge stored energy!", "VFD software takes time to save", "To cool the heat sink"],
    correctAnswer: 1,
    explanation: "VFD DC bus capacitors store up to 800V DC. Internal bleed resistors require several minutes to safely drain charge.",
    targetProfiles: ["technician", "electrician", "engineer", "all"],
    category: "Motors & Controls"
  },
  {
    id: 180,
    question: "What is the purpose of an Arc Flash Sensor (Optical Arc Detection) in modern switchgear?",
    options: ["To take photos during maintenance", "To detect arc flash light within 1 millisecond and trigger ultra-fast breaker tripping before pressure builds up", "To light up cabinet interiors", "To measure ambient room lumens"],
    correctAnswer: 1,
    explanation: "Optical arc sensors combined with fast relays clear arc faults within 10-15ms, reducing blast damage by up to 90%.",
    targetProfiles: ["engineer", "electrician", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 181,
    question: "What is the primary danger of using damaged high-voltage hot sticks?",
    options: ["Hot sticks look dull", "Cracks or dirt on hot stick fiberglass shafts conduct high voltage directly to the operator's hands!", "Hot sticks bend slightly", "Hot sticks weigh more"],
    correctAnswer: 1,
    explanation: "Hot sticks rely on clean, un-cracked fiberglass surface resistance. Contamination creates tracking paths for high voltage.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Tool Safety"
  },
  {
    id: 182,
    question: "What is the safe procedure if a coworker contacts a high-voltage 11kV busbar and remains attached?",
    options: ["Grab their clothing to pull them", "Do NOT touch victim! Instantly open main circuit breaker or trip substation emergency trip switch!", "Use a wet wooden stick", "Throw water"],
    correctAnswer: 1,
    explanation: "At 11kV, touching a victim or using improper objects results in instant fatal electrocution. Isolate power source immediately.",
    targetProfiles: ["supervisor", "electrician", "technician", "engineer", "all"],
    category: "Emergency & CPR"
  },
  {
    id: 183,
    question: "What is the purpose of equipotential ground mats during high-voltage outdoor switching?",
    options: ["To keep boots clean", "To ensure operator's feet and hands on switch handles remain at identical electrical potential during switching", "To block weeds", "To cushion foot steps"],
    correctAnswer: 1,
    explanation: "Grounding mats bonded to switch handles eliminate touch potential voltage between hands and feet during fault events.",
    targetProfiles: ["electrician", "engineer", "all"],
    category: "Grounding Hazards"
  },
  {
    id: 184,
    question: "Why should electrical maintenance personnel wear ear protection (earplugs/earmuffs) inside switchrooms?",
    options: ["Switchrooms are noisy from fans", "Arc flash blast sound pressure levels can exceed 140-165 dB, causing permanent eardrum rupture!", "To block radio chatter", "To keep ears warm"],
    correctAnswer: 1,
    explanation: "Arc blast pressure waves generate acoustic impulses exceeding 140 dB. Hearing protection is mandatory inside arc boundaries.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "PPE Selection"
  },
  {
    id: 185,
    question: "What does an Electrical One-Line Diagram (SLD) display?",
    options: ["Building floor plan", "A simplified schematic showing power flow, transformers, switchgear, breakers, ratings, and system interconnections", "Cable tray colors", "Factory employee roster"],
    correctAnswer: 1,
    explanation: "One-line diagrams provide essential schematics for switching plans, fault calculations, and LOTO isolation points.",
    targetProfiles: ["engineer", "supervisor", "electrician", "all"],
    category: "System Protection"
  },
  {
    id: 186,
    question: "Why should you never use water-based fire extinguishers inside an energized data center or control room?",
    options: ["Water ruins carpet", "Water conducts electricity to the operator and permanently destroys live sensitive electronic servers!", "Water freezes fast", "Water turns brown"],
    correctAnswer: 1,
    explanation: "Water conducts current and ruins electronics. Clean agent systems (FM-200, Novec 1230, CO2) extinguish fires safely.",
    targetProfiles: ["supervisor", "engineer", "technician", "all"],
    category: "Emergency & CPR"
  },
  {
    id: 187,
    question: "What is the function of a Neutral Grounding Resistor (NGR) in industrial electrical systems?",
    options: ["To heat sub-stations", "To limit ground fault current to a safe value (e.g. 5A or 400A), preventing arc blast damage and equipment destruction", "To balance phase voltages", "To improve motor power factor"],
    correctAnswer: 1,
    explanation: "NGRs connected between transformer neutral and ground limit phase-to-ground fault currents to manageable levels.",
    targetProfiles: ["engineer", "electrician", "all"],
    category: "System Protection"
  },
  {
    id: 188,
    question: "What is the purpose of an Automatic Transfer Switch (ATS) in critical facility power networks?",
    options: ["To switch motor speeds", "To automatically transfer load connections from normal utility power to emergency standby generators during grid outages", "To change lighting colors", "To meter solar output"],
    correctAnswer: 1,
    explanation: "ATS panels monitor grid voltage and seamlessly switch facility power to emergency backup generators upon utility failure.",
    targetProfiles: ["engineer", "supervisor", "technician", "all"],
    category: "System Protection"
  },
  {
    id: 189,
    question: "Why must leather work boots used in industrial electrical plants have Dielectric / EH (Electrical Hazard) ratings?",
    options: ["EH boots look stylish", "EH rated soles provide secondary electric shock protection against 18,000V AC at 60Hz under dry conditions", "EH boots resist mud", "EH soles wear longer"],
    correctAnswer: 1,
    explanation: "EH footwear features non-conductive, shock-resistant soles tested to prevent current from grounding through your feet.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "PPE Selection"
  },
  {
    id: 190,
    question: "What is the main risk of opening an energized high-voltage knife switch without quick-break arc chutes?",
    options: ["The handle slips", "An uncontained electric arc stretches through open air, ionizes surrounding oxygen, and causes massive phase short circuits", "The switch turns warm", "The lights dim slightly"],
    correctAnswer: 1,
    explanation: "Arc chutes cool and split electric arcs. Open knife switches without arc chutes sustain arcs across open switch bays.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Switching Safety"
  },
  {
    id: 191,
    question: "What is the golden rule before touching any de-energized electrical conductor during maintenance?",
    options: ["Assuming it is dead if the lights are off", "TEST BEFORE TOUCH! Verify zero voltage using a tested meter, apply temporary grounds, and wear rated PPE", "Touch quickly with index finger", "Smell the wire for smoke"],
    correctAnswer: 1,
    explanation: "Always test with a verified meter before touching any conductor. Treat every wire as live until proven otherwise!",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 192,
    question: "What is the purpose of an Electrical Arc Flash Risk Assessment?",
    options: ["To determine room paint colors", "To calculate potential incident energy levels, boundaries, and required PPE for all facility electrical assets", "To calculate electric bills", "To count wall sockets"],
    correctAnswer: 1,
    explanation: "Arc flash risk assessments analyze fault levels and clearing times to establish safe working boundaries and PPE specs.",
    targetProfiles: ["engineer", "supervisor", "all"],
    category: "Arc Flash Safety"
  },
  {
    id: 193,
    question: "What is the function of a Lockout Tagout Hasp on a main breaker handle?",
    options: ["To decorate the panel", "To allow multiple locks so no single person can re-energize equipment while others are still working", "To keep breaker handle upright", "To prevent dust buildup"],
    correctAnswer: 1,
    explanation: "Hasps ensure every team member maintains individual padlock protection over the isolation point.",
    targetProfiles: ["supervisor", "electrician", "technician", "all"],
    category: "LOTO & Isolation"
  },
  {
    id: 194,
    question: "Why should electrical maintenance personnel NEVER wear clothing made of 100% untreated synthetic fabrics like nylon or polyester?",
    options: ["Synthetic clothes shrink in wash", "Under arc flash heat, synthetics melt into liquid plastic, fusing into human skin tissue and worsening burn severity", "Synthetics fade in sunlight", "Synthetics hold static dust"],
    correctAnswer: 1,
    explanation: "Melting fabrics trap intense heat against skin. Wear 100% natural cotton or certified flame-resistant (FR) fabrics.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "PPE Selection"
  },
  {
    id: 195,
    question: "What is the danger of working alone inside a high-voltage substation without communication devices?",
    options: ["Boredom", "In case of shock or arc flash injury, no one is available to initiate emergency response or perform CPR", "Work takes longer", "Substation gates lock"],
    correctAnswer: 1,
    explanation: "High-voltage environments require buddy systems and active communication channels for immediate emergency aid.",
    targetProfiles: ["supervisor", "engineer", "electrician", "all"],
    category: "Emergency & CPR"
  },
  {
    id: 196,
    question: "What does an NFPA 70E Category 4 Arc Flash Suit consist of?",
    options: ["Cotton shirt and safety glasses", "Multi-layer arc suit hood, coat, bib trousers rated minimum 40 cal/cm², voltage gloves, leather protectors, and EH boots", "Standard rain coat", "High visibility vest only"],
    correctAnswer: 1,
    explanation: "Category 4 protects against extreme incident energy (≥40 cal/cm²) using heavy multi-layer flame-resistant suits.",
    targetProfiles: ["electrician", "technician", "engineer", "all"],
    category: "PPE Selection"
  },
  {
    id: 197,
    question: "What is the purpose of an Insulated Hot Stick in high-voltage utility switching?",
    options: ["To clear tree branches only", "To allow linemen to safely operate high-voltage disconnect switches and fuses from outside safe approach boundaries", "To measure pole height", "To support heavy cables"],
    correctAnswer: 1,
    explanation: "Hot sticks use rated fiberglass insulation to provide mechanical distance and electrical isolation during switching.",
    targetProfiles: ["electrician", "technician", "all"],
    category: "Tool Safety"
  },
  {
    id: 198,
    question: "What should you do if an electric motor smells like burning insulation and emits white smoke?",
    options: ["Keep motor running and throw water", "Hit Emergency Stop / disconnect breaker immediately and apply LOTO before inspection", "Increase motor speed", "Blow compressed air"],
    correctAnswer: 1,
    explanation: "De-energize burning motors immediately to stop internal winding fires and prevent phase-to-ground shorts.",
    targetProfiles: ["technician", "electrician", "supervisor", "all"],
    category: "Motors & Controls"
  },
  {
    id: 199,
    question: "What is the primary function of a Ground Fault Circuit Interrupter (GFCI) device?",
    options: ["To regulate line voltage", "To detect dangerous current leaks to ground and instantly break the circuit before electrocution occurs", "To increase current output", "To save energy"],
    correctAnswer: 1,
    explanation: "GFCIs detect imbalance between hot and neutral conductors, cutting power within milliseconds to save lives.",
    targetProfiles: ["electrician", "technician", "engineer", "supervisor", "all"],
    category: "System Protection"
  },
  {
    id: 200,
    question: "What is the ultimate objective of all electrical safety procedures and regulations?",
    options: ["To pass inspections only", "To protect human life, eliminate electrical shock and arc flash injuries, and ensure zero workplace fatalities!", "To fill out paperwork", "To slow down plant operations"],
    correctAnswer: 1,
    explanation: "Electrical safety protocols exist to ensure every worker returns home safely to their family at the end of every shift.",
    targetProfiles: ["supervisor", "engineer", "electrician", "technician", "all"],
    category: "Basic Safety"
  }
];
